### ISSUE TITLE
should i need some glue if i use the thermalpad! or i just put it on the limesdr !?

### ISSUE THREAD

**Issue by Dastgsm** [gasparka/spectrogram#12]
should i need some specific glue if i use the thermalpad! or i just put it on the limesdr !?

_Originally posted by @Dastgsm in https://github.com/gasparka/spectrogram/issues/11#issuecomment-462779228_

**Comment by gasparka** [comment]
I just put it on and then fix the radiator with screws.

**Comment by Dastgsm** [comment]
Thank's a lot, it's very helpful

**Comment by Dastgsm** [comment]
for the photo on the github with limesdrmini,why didn't you use thermalpad on the pad but directly with aluminium ?

**Comment by gasparka** [comment]
Sorry, i don't understand your question.

**Comment by Dastgsm** [comment]
i see that you use aluminium cooling in the top of the fpga!! why didn't you thermalpad? it's not more performant?

**Comment by gasparka** [comment]
Ah ok, in this case i used thermal paste.
