### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Dastgsm** [gasparka/spectrogram#13]
Hey,
if i use a default gateware of limesdrmini on source for the installation! or i need some modification of it before use it! how to install proprely it?

Chears,

**Comment by gasparka** [comment]
Gateware is programmed automatically when you execute the 'spectrogram' binary.

**Comment by Dastgsm** [comment]
And how about the dimension of the heatsink with the thermal pad down to  the limesdrmini? and the dimension also of the heatsink with your fpga?


Chears,

**Comment by gasparka** [comment]
These are just some random metals i found, i don't have the measurements.

**Comment by Dastgsm** [comment]
Hey @gasparka , until now, about time , how long did you use it for a max? and how many times. I'm testing OAI with my limesdrmini and i break it because it's no heatsink! that why i would like more information for precaution!!!

**Comment by gasparka** [comment]
I have used the version with large heatsink for hours and many times.

**Comment by Dastgsm** [comment]
is it possible to give me the dimension just for having idea for the two heatsinks?

**Comment by gasparka** [comment]
Sorry no, i don't have access to them anymore.
