### ISSUE TITLE
Devices for schematic cooler

### ISSUE THREAD

**Issue by Dastgsm** [gasparka/spectrogram#21]
hello,
Please, i would like to ask you : 
What kind of device did you use for having a real schematic experimentation of dissipation of the temperature like of this photo.
https://github.com/gasparka/spectrogram/blob/master/doc/no_cools.JPG ?

Where could i buy device having this dissipation temperature?

Chears,

**Comment by gasparka** [comment]
I used https://www.flir.com/flir-one/.
