### ISSUE TITLE
What's the problem when it is at 140MHz?

### ISSUE THREAD

**Issue by juzhang74** [gasparka/spectrogram#22]
Hi, 
 I meet a strange problem with this program.
 When it running at 2.4GHz, all seems OK.
 If I set the central freq at 140MHz, with GNURadio and the official FPGA, all things seems OK, but at the same central freq, spectrogram's outputs has nothing except noise floor.
Could anyone tell me why? Any advice will be appreciated.

**Comment by gasparka** [comment]
Hi
You can press Control + j to open SDR configuration sidebar. Antenna selection should be already at "Auto", but maybe you need to increase the gain?

**Comment by juzhang74** [comment]
Yes-ish!!!
I can see signals at 140MHz with LNA gain set to 20.
Thanks a lot!

**Comment by gasparka** [comment]
LNA should be by default set to 30. Did you mean VGA, or maybe we are dealing with some bug here?

**Comment by juzhang74** [comment]
We use your usage_demo.ipynb demo. And in this demo, Default gains are set to "gains = {LNA: 0, TIA: 0, PGA: -12}". That's the problem. When I set LNA gain to 20, all seems Ok!

**Comment by juzhang74** [comment]
Thank you very much!
