### ISSUE TITLE
Raspberry PI 3B and Raspberry PI OS 2020-08-20-raspios-buster-armhf.zip and spectrogram as of today.

### ISSUE THREAD

**Issue by tdbone1** [gasparka/spectrogram#24]
working perfect!
just wanted to say thanks gasparka!

all i did was fresh install of mention OS.
sudo apt update
sudo apt upgrade
sudo apt dist-upgrade
sudo apt clean
pip3 install spectrogram (the installer stops and has you run some manual commands but works fine)
spectrogram

I have two laptops (one with ubuntu 20.04 amd64 desktop) and (the other is running ubuntu amd64 desktop 18.04)
both are fully updated but i get 
QStandardPaths: error creating runtime directory /tmp/runtime-root: No such file or directory
dbus[1]: The last reference on a connection was dropped without closing the connection. This is a bug in an application. See dbus_connection_unref() documentation for details.
Most likely, the application was supposed to call dbus_connection_close(), since this is a private connection.
D-Bus not built with -rdynamic so unable to print a backtrace
2020-10-14 12:36:02.244 | INFO | main:main:167 - Killing local server...
spectrogram_server
2020-10-14 12:36:02.539 | INFO | main:main:170 - Done!

as i reported before.

i was told to install 18.04 but i did and it isnt working very easily with my knowledge.
any advice would be great.

**Comment by gasparka** [comment]
Closing this, because there is a similiar topic where we discuss!
